USE springblog_db;

insert into posts (title, body) values ('Synergistic reciprocal concept', 'mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus');
insert into posts (title, body) values ('Up-sized static productivity', 'vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat');
insert into posts (title, body) values ('Re-engineered intermediate pricing structure', 'a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut');
insert into posts (title, body) values ('Synergistic multi-state neural-net', 'nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo');
insert into posts (title, body) values ('Horizontal zero defect migration', 'proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque');
insert into posts (title, body) values ('Ergonomic national infrastructure', 'vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id');
insert into posts (title, body) values ('Vision-oriented zero tolerance installation', 'quam sapien varius ut blandit non interdum in ante vestibulum ante ipsum primis in faucibus orci');
insert into posts (title, body) values ('Intuitive zero defect core', 'elementum nullam varius nulla facilisi cras non velit nec nisi');
insert into posts (title, body) values ('Networked needs-based knowledge user', 'in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa');
insert into posts (title, body) values ('Function-based incremental neural-net', 'orci mauris lacinia sapien quis libero nullam sit amet turpis elementum');
insert into posts (title, body) values ('Front-line dedicated data-warehouse', 'augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea');
insert into posts (title, body) values ('Business-focused directional software', 'amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in');
insert into posts (title, body) values ('Customizable 5th generation instruction set', 'sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend');
insert into posts (title, body) values ('Intuitive zero administration projection', 'vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices');
insert into posts (title, body) values ('Sharable multi-state flexibility', 'purus sit amet nulla quisque arcu libero rutrum ac lobortis vel dapibus at diam nam tristique');
insert into posts (title, body) values ('Universal zero defect algorithm', 'sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula');
insert into posts (title, body) values ('Future-proofed asynchronous toolset', 'magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in');
insert into posts (title, body) values ('Organic 3rd generation help-desk', 'vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin');
insert into posts (title, body) values ('Re-engineered reciprocal utilisation', 'platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius');
insert into posts (title, body) values ('Implemented transitional website', 'rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus');